# @package _global_

smoothing_type: kernel_moving_average
smoothing_params:
  kernel_size_mag: 10
  kernel_size_phase: 10
  mode: mean
  min_valid_samples: 1
  max_time_diff: 0.1
norm: unit
norm_range: self
align_tdoa: true
tdoa_correction:
  kernel_size: 10
  max_time_diff: 0.1
  filter_type: median
dataset_config:
  train:
    dataset_type: FingerprintingDataset
    dataset_params:
      file_path: ./data/corridor_train.h5
      smoothing_type: ${smoothing_type}
      smoothing_params: ${smoothing_params}
      norm: ${norm}
      norm_range: ${norm_range}
      tdoa_correction: ${tdoa_correction}
      align_tdoa: ${align_tdoa}
      augmentations:
      - augmentation_name: IQToAbs
        augmentation_params:
          keep_iq: false
eval_config:
  train:
    output_path: ${output_dir}/train
    dataset_config:
      dataset_type: FingerprintingDataset
      dataset_params:
        file_path: ./data/corridor_train.h5
        smoothing_type: ${smoothing_type}
        smoothing_params: ${smoothing_params}
        norm: ${norm}
        norm_range: ${norm_range}
        tdoa_correction: ${tdoa_correction}
        align_tdoa: ${align_tdoa}
        augmentations:
        - augmentation_name: IQToAbs
          augmentation_params:
            keep_iq: false
  test:
    output_path: ${output_dir}/test
    dataset_config:
      dataset_type: FingerprintingDataset
      dataset_params:
        file_path: ./data/corridor_test.h5
        smoothing_type: ${smoothing_type}
        smoothing_params: ${smoothing_params}
        norm: ${norm}
        norm_range: ${norm_range}
        tdoa_correction: ${tdoa_correction}
        align_tdoa: ${align_tdoa}
        augmentations:
        - augmentation_name: IQToAbs
          augmentation_params:
            keep_iq: false
dimensionality_reduction_config:
  dimensionality_reduction_type: Isomap
  dimensionality_reduction_params:
    n_components: 2
    n_neighbors: 20
    metric: manhattan
  fit_reduction: 10
output_dir: ./experiments/corridor/Isomap/${now:%Y-%m-%d_%H-%M-%S}
dataloader_config:
  train:
    num_workers: 8
    persistent_workers: true
    shuffle: true
    batch_size: 1024
  eval:
    num_workers: 8
    persistent_workers: true
    shuffle: false
    batch_size: 4096
seed: 55492